version: '3.8'

services:
  # frontend-next:
  #   build: ./frontend-next
  #   ports:
  #     - "3000:3000"

  # backend-node:
  #   build: ./backend-node
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - mongo
  #   environment:
  #     - MONGO_HOST=mongo

  # ai-service:
  #   build: ./ai-service
  #   ports:
  #     - "5000:5000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
